version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: order_tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 4000
      JWT_SECRET: dev-secret
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: order_tracking
      DB_USER: postgres
      DB_PASS: postgres
      DB_SSL: "false"
    depends_on:
      - db
    ports:
      - "4000:4000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: "/api"
      VITE_API_PROXY_TARGET: "http://server:4000"
    depends_on:
      - server
    ports:
      - "5173:5173"
volumes:
  db_data:

